import { Code } from '@/components/code'
import Head from 'next/head'

export default function FisrtStep() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                {/* <script src="https://unpkg.com/shiki"></script> */}
            </Head>
            <div>
                <h2>Instalação e importação</h2>
                <p>A biblioteca <strong>rna.js</strong> pode ser usada tanto em paginas web estáticas quanto em aplicações <a href="">node</a>.</p>
                <h3>Páginas Web</h3>
                <p>Para instalar em páginas web, ou seja, no frontend, adicione a seguinte linha de código á tag head do seu html:</p>
                <code>
                    <Code code={'<script src="https://rnajs.vercel.app/api/rna"></script>'} lang="html"></Code>
                </code>
            </div>
        </>
    )
}